/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'description' : IDL.Text,
  'docType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const PaperSize = IDL.Variant({
  'a4' : IDL.Null,
  'a5' : IDL.Null,
  'legal' : IDL.Null,
  'letter' : IDL.Null,
});
export const LetterStatus = IDL.Variant({
  'finalized' : IDL.Null,
  'draft' : IDL.Null,
});
export const Letter = IDL.Record({
  'status' : LetterStatus,
  'referenceNumber' : IDL.Text,
  'subject' : IDL.Text,
  'authorityName' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Int,
  'designation' : IDL.Text,
  'createdAt' : IDL.Int,
  'paperSize' : PaperSize,
  'recipientAddress' : IDL.Text,
  'recipientName' : IDL.Text,
});
export const AdminRole = IDL.Variant({
  'admin' : IDL.Null,
  'standard' : IDL.Null,
});
export const UserCreatePayload = IDL.Record({
  'username' : IDL.Text,
  'role' : AdminRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'profilePhotoBlob' : IDL.Opt(ExternalBlob),
  'passwordHash' : IDL.Vec(IDL.Nat8),
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : AdminRole,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'profilePhotoBlob' : IDL.Opt(ExternalBlob),
  'passwordHash' : IDL.Vec(IDL.Nat8),
  'phone' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const FranchiseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FranchiseApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : FranchiseStatus,
  'areaPreference' : IDL.Text,
  'investmentCapacity' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'adminNote' : IDL.Text,
  'businessExperience' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const KYCStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const KYCRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : KYCStatus,
  'userId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'panNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : ExternalBlob,
  'verifiedAt' : IDL.Opt(IDL.Int),
  'panDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
});
export const LoanStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LoanApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : LoanStatus,
  'documents' : IDL.Text,
  'loanAmount' : IDL.Nat,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'adminNote' : IDL.Text,
  'address' : IDL.Text,
  'existingLoans' : IDL.Text,
  'phone' : IDL.Text,
  'purpose' : IDL.Text,
  'monthlyIncome' : IDL.Text,
});
export const Credentials = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Vec(IDL.Nat8),
});
export const LoginAttempt = IDL.Record({
  'id' : IDL.Text,
  'credentials' : Credentials,
});
export const FranchiseApplicationCreatePayload = IDL.Record({
  'areaPreference' : IDL.Text,
  'investmentCapacity' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'businessExperience' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const KYCRecordCreatePayload = IDL.Record({
  'userId' : IDL.Text,
  'panNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : ExternalBlob,
  'panDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
});
export const LoanApplicationCreatePayload = IDL.Record({
  'documents' : IDL.Text,
  'loanAmount' : IDL.Nat,
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'address' : IDL.Text,
  'existingLoans' : IDL.Text,
  'phone' : IDL.Text,
  'purpose' : IDL.Text,
  'monthlyIncome' : IDL.Text,
});
export const FranchiseApplicationUpdatePayload = IDL.Record({
  'id' : IDL.Text,
  'application' : FranchiseApplicationCreatePayload,
});
export const KYCRecordUpdatePayload = IDL.Record({
  'id' : IDL.Text,
  'record' : KYCRecordCreatePayload,
});
export const LoanApplicationUpdatePayload = IDL.Record({
  'id' : IDL.Text,
  'application' : LoanApplicationCreatePayload,
});
export const UserUpdatePayload = IDL.Record({
  'id' : IDL.Text,
  'user' : UserCreatePayload,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [Document],
      [],
    ),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [GalleryItem],
      [],
    ),
  'approveFranchiseApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveLoanApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createLetter' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PaperSize,
        LetterStatus,
      ],
      [Letter],
      [],
    ),
  'createUser' : IDL.Func([UserCreatePayload], [User], []),
  'deactivateUser' : IDL.Func([IDL.Text], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLetter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAllFranchiseApplications' : IDL.Func(
      [],
      [IDL.Vec(FranchiseApplication)],
      ['query'],
    ),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllKYCRecords' : IDL.Func([], [IDL.Vec(KYCRecord)], ['query']),
  'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
  'getAllLoanApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  'getFranchiseApplication' : IDL.Func(
      [IDL.Text],
      [FranchiseApplication],
      ['query'],
    ),
  'getGalleryItem' : IDL.Func([IDL.Text], [IDL.Opt(GalleryItem)], ['query']),
  'getKYCRecord' : IDL.Func([IDL.Text], [KYCRecord], ['query']),
  'getLetter' : IDL.Func([IDL.Text], [IDL.Opt(Letter)], ['query']),
  'getLoanApplication' : IDL.Func([IDL.Text], [LoanApplication], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalGalleryItems' : IDL.Nat,
          'totalKYC' : IDL.Nat,
          'totalLoans' : IDL.Nat,
          'totalFranchises' : IDL.Nat,
          'totalLetters' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalDocuments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Text], [User], ['query']),
  'loginUser' : IDL.Func(
      [LoginAttempt],
      [IDL.Record({ 'user' : IDL.Opt(User), 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'rejectFranchiseApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectKYC' : IDL.Func([IDL.Text], [], []),
  'rejectLoanApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitFranchiseApplication' : IDL.Func(
      [FranchiseApplicationCreatePayload],
      [FranchiseApplication],
      [],
    ),
  'submitKYC' : IDL.Func([KYCRecordCreatePayload], [KYCRecord], []),
  'submitLoanApplication' : IDL.Func(
      [LoanApplicationCreatePayload],
      [LoanApplication],
      [],
    ),
  'updateDocument' : IDL.Func([IDL.Text, Document], [IDL.Bool], []),
  'updateFranchiseApplication' : IDL.Func(
      [FranchiseApplicationUpdatePayload],
      [FranchiseApplication],
      [],
    ),
  'updateGalleryItem' : IDL.Func([IDL.Text, GalleryItem], [IDL.Bool], []),
  'updateKYCRecord' : IDL.Func([KYCRecordUpdatePayload], [KYCRecord], []),
  'updateLetter' : IDL.Func([IDL.Text, Letter], [IDL.Bool], []),
  'updateLoanApplication' : IDL.Func(
      [LoanApplicationUpdatePayload],
      [LoanApplication],
      [],
    ),
  'updateUser' : IDL.Func([UserUpdatePayload], [User], []),
  'verifyKYC' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'description' : IDL.Text,
    'docType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const PaperSize = IDL.Variant({
    'a4' : IDL.Null,
    'a5' : IDL.Null,
    'legal' : IDL.Null,
    'letter' : IDL.Null,
  });
  const LetterStatus = IDL.Variant({
    'finalized' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Letter = IDL.Record({
    'status' : LetterStatus,
    'referenceNumber' : IDL.Text,
    'subject' : IDL.Text,
    'authorityName' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Int,
    'designation' : IDL.Text,
    'createdAt' : IDL.Int,
    'paperSize' : PaperSize,
    'recipientAddress' : IDL.Text,
    'recipientName' : IDL.Text,
  });
  const AdminRole = IDL.Variant({ 'admin' : IDL.Null, 'standard' : IDL.Null });
  const UserCreatePayload = IDL.Record({
    'username' : IDL.Text,
    'role' : AdminRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'profilePhotoBlob' : IDL.Opt(ExternalBlob),
    'passwordHash' : IDL.Vec(IDL.Nat8),
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : AdminRole,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'profilePhotoBlob' : IDL.Opt(ExternalBlob),
    'passwordHash' : IDL.Vec(IDL.Nat8),
    'phone' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const FranchiseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FranchiseApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : FranchiseStatus,
    'areaPreference' : IDL.Text,
    'investmentCapacity' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'adminNote' : IDL.Text,
    'businessExperience' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const KYCStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const KYCRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : KYCStatus,
    'userId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'panNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : ExternalBlob,
    'verifiedAt' : IDL.Opt(IDL.Int),
    'panDoc' : ExternalBlob,
    'aadhaarDoc' : ExternalBlob,
  });
  const LoanStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LoanApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : LoanStatus,
    'documents' : IDL.Text,
    'loanAmount' : IDL.Nat,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'adminNote' : IDL.Text,
    'address' : IDL.Text,
    'existingLoans' : IDL.Text,
    'phone' : IDL.Text,
    'purpose' : IDL.Text,
    'monthlyIncome' : IDL.Text,
  });
  const Credentials = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Vec(IDL.Nat8),
  });
  const LoginAttempt = IDL.Record({
    'id' : IDL.Text,
    'credentials' : Credentials,
  });
  const FranchiseApplicationCreatePayload = IDL.Record({
    'areaPreference' : IDL.Text,
    'investmentCapacity' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'businessExperience' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const KYCRecordCreatePayload = IDL.Record({
    'userId' : IDL.Text,
    'panNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : ExternalBlob,
    'panDoc' : ExternalBlob,
    'aadhaarDoc' : ExternalBlob,
  });
  const LoanApplicationCreatePayload = IDL.Record({
    'documents' : IDL.Text,
    'loanAmount' : IDL.Nat,
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'address' : IDL.Text,
    'existingLoans' : IDL.Text,
    'phone' : IDL.Text,
    'purpose' : IDL.Text,
    'monthlyIncome' : IDL.Text,
  });
  const FranchiseApplicationUpdatePayload = IDL.Record({
    'id' : IDL.Text,
    'application' : FranchiseApplicationCreatePayload,
  });
  const KYCRecordUpdatePayload = IDL.Record({
    'id' : IDL.Text,
    'record' : KYCRecordCreatePayload,
  });
  const LoanApplicationUpdatePayload = IDL.Record({
    'id' : IDL.Text,
    'application' : LoanApplicationCreatePayload,
  });
  const UserUpdatePayload = IDL.Record({
    'id' : IDL.Text,
    'user' : UserCreatePayload,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [Document],
        [],
      ),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [GalleryItem],
        [],
      ),
    'approveFranchiseApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveLoanApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createLetter' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PaperSize,
          LetterStatus,
        ],
        [Letter],
        [],
      ),
    'createUser' : IDL.Func([UserCreatePayload], [User], []),
    'deactivateUser' : IDL.Func([IDL.Text], [], []),
    'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLetter' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAllFranchiseApplications' : IDL.Func(
        [],
        [IDL.Vec(FranchiseApplication)],
        ['query'],
      ),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllKYCRecords' : IDL.Func([], [IDL.Vec(KYCRecord)], ['query']),
    'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
    'getAllLoanApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
    'getFranchiseApplication' : IDL.Func(
        [IDL.Text],
        [FranchiseApplication],
        ['query'],
      ),
    'getGalleryItem' : IDL.Func([IDL.Text], [IDL.Opt(GalleryItem)], ['query']),
    'getKYCRecord' : IDL.Func([IDL.Text], [KYCRecord], ['query']),
    'getLetter' : IDL.Func([IDL.Text], [IDL.Opt(Letter)], ['query']),
    'getLoanApplication' : IDL.Func([IDL.Text], [LoanApplication], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalGalleryItems' : IDL.Nat,
            'totalKYC' : IDL.Nat,
            'totalLoans' : IDL.Nat,
            'totalFranchises' : IDL.Nat,
            'totalLetters' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalDocuments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text], [User], ['query']),
    'loginUser' : IDL.Func(
        [LoginAttempt],
        [IDL.Record({ 'user' : IDL.Opt(User), 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'rejectFranchiseApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectKYC' : IDL.Func([IDL.Text], [], []),
    'rejectLoanApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitFranchiseApplication' : IDL.Func(
        [FranchiseApplicationCreatePayload],
        [FranchiseApplication],
        [],
      ),
    'submitKYC' : IDL.Func([KYCRecordCreatePayload], [KYCRecord], []),
    'submitLoanApplication' : IDL.Func(
        [LoanApplicationCreatePayload],
        [LoanApplication],
        [],
      ),
    'updateDocument' : IDL.Func([IDL.Text, Document], [IDL.Bool], []),
    'updateFranchiseApplication' : IDL.Func(
        [FranchiseApplicationUpdatePayload],
        [FranchiseApplication],
        [],
      ),
    'updateGalleryItem' : IDL.Func([IDL.Text, GalleryItem], [IDL.Bool], []),
    'updateKYCRecord' : IDL.Func([KYCRecordUpdatePayload], [KYCRecord], []),
    'updateLetter' : IDL.Func([IDL.Text, Letter], [IDL.Bool], []),
    'updateLoanApplication' : IDL.Func(
        [LoanApplicationUpdatePayload],
        [LoanApplication],
        [],
      ),
    'updateUser' : IDL.Func([UserUpdatePayload], [User], []),
    'verifyKYC' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };