/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminRole = { 'admin' : null } |
  { 'standard' : null };
export interface Credentials { 'username' : string, 'password' : Uint8Array }
export interface Document {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'description' : string,
  'docType' : string,
  'uploadedAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FranchiseApplication {
  'id' : string,
  'status' : FranchiseStatus,
  'areaPreference' : string,
  'investmentCapacity' : string,
  'city' : string,
  'userId' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'adminNote' : string,
  'businessExperience' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
}
export interface FranchiseApplicationCreatePayload {
  'areaPreference' : string,
  'investmentCapacity' : string,
  'city' : string,
  'userId' : string,
  'fullName' : string,
  'businessExperience' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
}
export interface FranchiseApplicationUpdatePayload {
  'id' : string,
  'application' : FranchiseApplicationCreatePayload,
}
export type FranchiseStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'category' : string,
  'uploadedAt' : bigint,
}
export interface KYCRecord {
  'id' : string,
  'status' : KYCStatus,
  'userId' : string,
  'submittedAt' : bigint,
  'panNumber' : string,
  'aadhaarNumber' : string,
  'photo' : ExternalBlob,
  'verifiedAt' : [] | [bigint],
  'panDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
}
export interface KYCRecordCreatePayload {
  'userId' : string,
  'panNumber' : string,
  'aadhaarNumber' : string,
  'photo' : ExternalBlob,
  'panDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
}
export interface KYCRecordUpdatePayload {
  'id' : string,
  'record' : KYCRecordCreatePayload,
}
export type KYCStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface Letter {
  'status' : LetterStatus,
  'referenceNumber' : string,
  'subject' : string,
  'authorityName' : string,
  'body' : string,
  'date' : bigint,
  'designation' : string,
  'createdAt' : bigint,
  'paperSize' : PaperSize,
  'recipientAddress' : string,
  'recipientName' : string,
}
export type LetterStatus = { 'finalized' : null } |
  { 'draft' : null };
export interface LoanApplication {
  'id' : string,
  'status' : LoanStatus,
  'documents' : string,
  'loanAmount' : bigint,
  'userId' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'adminNote' : string,
  'address' : string,
  'existingLoans' : string,
  'phone' : string,
  'purpose' : string,
  'monthlyIncome' : string,
}
export interface LoanApplicationCreatePayload {
  'documents' : string,
  'loanAmount' : bigint,
  'userId' : string,
  'fullName' : string,
  'address' : string,
  'existingLoans' : string,
  'phone' : string,
  'purpose' : string,
  'monthlyIncome' : string,
}
export interface LoanApplicationUpdatePayload {
  'id' : string,
  'application' : LoanApplicationCreatePayload,
}
export type LoanStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface LoginAttempt { 'id' : string, 'credentials' : Credentials }
export type PaperSize = { 'a4' : null } |
  { 'a5' : null } |
  { 'legal' : null } |
  { 'letter' : null };
export interface User {
  'id' : string,
  'username' : string,
  'createdAt' : bigint,
  'role' : AdminRole,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'profilePhotoBlob' : [] | [ExternalBlob],
  'passwordHash' : Uint8Array,
  'phone' : string,
  'walletBalance' : bigint,
}
export interface UserCreatePayload {
  'username' : string,
  'role' : AdminRole,
  'fullName' : string,
  'email' : string,
  'profilePhotoBlob' : [] | [ExternalBlob],
  'passwordHash' : Uint8Array,
  'phone' : string,
}
export interface UserUpdatePayload { 'id' : string, 'user' : UserCreatePayload }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDocument' : ActorMethod<
    [string, string, string, ExternalBlob, bigint],
    Document
  >,
  'addGalleryImage' : ActorMethod<
    [string, string, string, ExternalBlob],
    GalleryItem
  >,
  'approveFranchiseApplication' : ActorMethod<[string, string], undefined>,
  'approveLoanApplication' : ActorMethod<[string, string], undefined>,
  'createLetter' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      PaperSize,
      LetterStatus,
    ],
    Letter
  >,
  'createUser' : ActorMethod<[UserCreatePayload], User>,
  'deactivateUser' : ActorMethod<[string], undefined>,
  'deleteDocument' : ActorMethod<[string], boolean>,
  'deleteGalleryItem' : ActorMethod<[string], boolean>,
  'deleteLetter' : ActorMethod<[string], boolean>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllFranchiseApplications' : ActorMethod<[], Array<FranchiseApplication>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllKYCRecords' : ActorMethod<[], Array<KYCRecord>>,
  'getAllLetters' : ActorMethod<[], Array<Letter>>,
  'getAllLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getDocument' : ActorMethod<[string], [] | [Document]>,
  'getFranchiseApplication' : ActorMethod<[string], FranchiseApplication>,
  'getGalleryItem' : ActorMethod<[string], [] | [GalleryItem]>,
  'getKYCRecord' : ActorMethod<[string], KYCRecord>,
  'getLetter' : ActorMethod<[string], [] | [Letter]>,
  'getLoanApplication' : ActorMethod<[string], LoanApplication>,
  'getStats' : ActorMethod<
    [],
    {
      'totalGalleryItems' : bigint,
      'totalKYC' : bigint,
      'totalLoans' : bigint,
      'totalFranchises' : bigint,
      'totalLetters' : bigint,
      'totalUsers' : bigint,
      'totalDocuments' : bigint,
    }
  >,
  'getUser' : ActorMethod<[string], User>,
  'loginUser' : ActorMethod<
    [LoginAttempt],
    { 'user' : [] | [User], 'error' : [] | [string] }
  >,
  'rejectFranchiseApplication' : ActorMethod<[string, string], undefined>,
  'rejectKYC' : ActorMethod<[string], undefined>,
  'rejectLoanApplication' : ActorMethod<[string, string], undefined>,
  'submitFranchiseApplication' : ActorMethod<
    [FranchiseApplicationCreatePayload],
    FranchiseApplication
  >,
  'submitKYC' : ActorMethod<[KYCRecordCreatePayload], KYCRecord>,
  'submitLoanApplication' : ActorMethod<
    [LoanApplicationCreatePayload],
    LoanApplication
  >,
  'updateDocument' : ActorMethod<[string, Document], boolean>,
  'updateFranchiseApplication' : ActorMethod<
    [FranchiseApplicationUpdatePayload],
    FranchiseApplication
  >,
  'updateGalleryItem' : ActorMethod<[string, GalleryItem], boolean>,
  'updateKYCRecord' : ActorMethod<[KYCRecordUpdatePayload], KYCRecord>,
  'updateLetter' : ActorMethod<[string, Letter], boolean>,
  'updateLoanApplication' : ActorMethod<
    [LoanApplicationUpdatePayload],
    LoanApplication
  >,
  'updateUser' : ActorMethod<[UserUpdatePayload], User>,
  'verifyKYC' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];