/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface KYCRecordUpdatePayload {
    id: string;
    record: KYCRecordCreatePayload;
}
export interface KYCRecordCreatePayload {
    userId: string;
    panNumber: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
    panDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}
export interface Letter {
    status: LetterStatus;
    referenceNumber: string;
    subject: string;
    authorityName: string;
    body: string;
    date: bigint;
    designation: string;
    createdAt: bigint;
    paperSize: PaperSize;
    recipientAddress: string;
    recipientName: string;
}
export interface KYCRecord {
    id: string;
    status: KYCStatus;
    userId: string;
    submittedAt: bigint;
    panNumber: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
    verifiedAt?: bigint;
    panDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}
export interface FranchiseApplicationUpdatePayload {
    id: string;
    application: FranchiseApplicationCreatePayload;
}
export interface FranchiseApplication {
    id: string;
    status: FranchiseStatus;
    areaPreference: string;
    investmentCapacity: string;
    city: string;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    businessExperience: string;
    state: string;
    address: string;
    phone: string;
}
export interface User {
    id: string;
    username: string;
    createdAt: bigint;
    role: AdminRole;
    fullName: string;
    isActive: boolean;
    email: string;
    profilePhotoBlob?: ExternalBlob;
    passwordHash: Uint8Array;
    phone: string;
    walletBalance: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: string;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    description: string;
    docType: string;
    uploadedAt: bigint;
}
export interface LoginAttempt {
    id: string;
    credentials: Credentials;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FranchiseApplicationCreatePayload {
    areaPreference: string;
    investmentCapacity: string;
    city: string;
    userId: string;
    fullName: string;
    businessExperience: string;
    state: string;
    address: string;
    phone: string;
}
export interface Credentials {
    username: string;
    password: Uint8Array;
}
export interface UserUpdatePayload {
    id: string;
    user: UserCreatePayload;
}
export interface LoanApplicationCreatePayload {
    documents: string;
    loanAmount: bigint;
    userId: string;
    fullName: string;
    address: string;
    existingLoans: string;
    phone: string;
    purpose: string;
    monthlyIncome: string;
}
export interface LoanApplicationUpdatePayload {
    id: string;
    application: LoanApplicationCreatePayload;
}
export interface LoanApplication {
    id: string;
    status: LoanStatus;
    documents: string;
    loanAmount: bigint;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    address: string;
    existingLoans: string;
    phone: string;
    purpose: string;
    monthlyIncome: string;
}
export interface UserCreatePayload {
    username: string;
    role: AdminRole;
    fullName: string;
    email: string;
    profilePhotoBlob?: ExternalBlob;
    passwordHash: Uint8Array;
    phone: string;
}
export interface GalleryItem {
    id: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
    uploadedAt: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AdminRole {
    admin = "admin",
    standard = "standard"
}
export enum FranchiseStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum KYCStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum LetterStatus {
    finalized = "finalized",
    draft = "draft"
}
export enum PaperSize {
    a4 = "a4",
    a5 = "a5",
    legal = "legal",
    letter = "letter"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addDocument(name: string, docType: string, description: string, blob: ExternalBlob, size: bigint): Promise<Document>;
    addGalleryImage(title: string, description: string, category: string, blob: ExternalBlob): Promise<GalleryItem>;
    approveFranchiseApplication(id: string, note: string): Promise<void>;
    approveLoanApplication(id: string, note: string): Promise<void>;
    createLetter(date: bigint, recipientName: string, recipientAddress: string, subject: string, body: string, authorityName: string, designation: string, paperSize: PaperSize, status: LetterStatus): Promise<Letter>;
    createUser(payload: UserCreatePayload): Promise<User>;
    deactivateUser(id: string): Promise<void>;
    deleteDocument(id: string): Promise<boolean>;
    deleteGalleryItem(id: string): Promise<boolean>;
    deleteLetter(referenceNumber: string): Promise<boolean>;
    getAllDocuments(): Promise<Array<Document>>;
    getAllFranchiseApplications(): Promise<Array<FranchiseApplication>>;
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    getAllKYCRecords(): Promise<Array<KYCRecord>>;
    getAllLetters(): Promise<Array<Letter>>;
    getAllLoanApplications(): Promise<Array<LoanApplication>>;
    getAllUsers(): Promise<Array<User>>;
    getDocument(id: string): Promise<Document | null>;
    getFranchiseApplication(id: string): Promise<FranchiseApplication>;
    getGalleryItem(id: string): Promise<GalleryItem | null>;
    getKYCRecord(id: string): Promise<KYCRecord>;
    getLetter(referenceNumber: string): Promise<Letter | null>;
    getLoanApplication(id: string): Promise<LoanApplication>;
    getStats(): Promise<{
        totalGalleryItems: bigint;
        totalKYC: bigint;
        totalLoans: bigint;
        totalFranchises: bigint;
        totalLetters: bigint;
        totalUsers: bigint;
        totalDocuments: bigint;
    }>;
    getUser(id: string): Promise<User>;
    loginUser(attempt: LoginAttempt): Promise<{
        user?: User;
        error?: string;
    }>;
    rejectFranchiseApplication(id: string, note: string): Promise<void>;
    rejectKYC(id: string): Promise<void>;
    rejectLoanApplication(id: string, note: string): Promise<void>;
    submitFranchiseApplication(payload: FranchiseApplicationCreatePayload): Promise<FranchiseApplication>;
    submitKYC(payload: KYCRecordCreatePayload): Promise<KYCRecord>;
    submitLoanApplication(payload: LoanApplicationCreatePayload): Promise<LoanApplication>;
    updateDocument(id: string, document: Document): Promise<boolean>;
    updateFranchiseApplication(payload: FranchiseApplicationUpdatePayload): Promise<FranchiseApplication>;
    updateGalleryItem(id: string, item: GalleryItem): Promise<boolean>;
    updateKYCRecord(payload: KYCRecordUpdatePayload): Promise<KYCRecord>;
    updateLetter(referenceNumber: string, letter: Letter): Promise<boolean>;
    updateLoanApplication(payload: LoanApplicationUpdatePayload): Promise<LoanApplication>;
    updateUser(payload: UserUpdatePayload): Promise<User>;
    verifyKYC(id: string): Promise<void>;
}
import type { AdminRole as _AdminRole, Document as _Document, ExternalBlob as _ExternalBlob, FranchiseApplication as _FranchiseApplication, FranchiseStatus as _FranchiseStatus, GalleryItem as _GalleryItem, KYCRecord as _KYCRecord, KYCRecordCreatePayload as _KYCRecordCreatePayload, KYCRecordUpdatePayload as _KYCRecordUpdatePayload, KYCStatus as _KYCStatus, Letter as _Letter, LetterStatus as _LetterStatus, LoanApplication as _LoanApplication, LoanStatus as _LoanStatus, PaperSize as _PaperSize, User as _User, UserCreatePayload as _UserCreatePayload, UserUpdatePayload as _UserUpdatePayload, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addDocument(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: bigint): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Document_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Document_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGalleryImage(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
                return from_candid_GalleryItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
            return from_candid_GalleryItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveFranchiseApplication(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFranchiseApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFranchiseApplication(arg0, arg1);
            return result;
        }
    }
    async approveLoanApplication(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLoanApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLoanApplication(arg0, arg1);
            return result;
        }
    }
    async createLetter(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: PaperSize, arg8: LetterStatus): Promise<Letter> {
        if (this.processError) {
            try {
                const result = await this.actor.createLetter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_PaperSize_n14(this._uploadFile, this._downloadFile, arg7), to_candid_LetterStatus_n16(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Letter_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLetter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_PaperSize_n14(this._uploadFile, this._downloadFile, arg7), to_candid_LetterStatus_n16(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Letter_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: UserCreatePayload): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(await to_candid_UserCreatePayload_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(await to_candid_UserCreatePayload_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteLetter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetter(arg0);
            return result;
        }
    }
    async getAllDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFranchiseApplications(): Promise<Array<FranchiseApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFranchiseApplications();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFranchiseApplications();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKYCRecords(): Promise<Array<KYCRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKYCRecords();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKYCRecords();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLetters(): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLetters();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLetters();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLoanApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoanApplications();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoanApplications();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFranchiseApplication(arg0: string): Promise<FranchiseApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.getFranchiseApplication(arg0);
                return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFranchiseApplication(arg0);
            return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItem(arg0: string): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItem(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItem(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKYCRecord(arg0: string): Promise<KYCRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getKYCRecord(arg0);
                return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKYCRecord(arg0);
            return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetter(arg0: string): Promise<Letter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetter(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetter(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanApplication(arg0: string): Promise<LoanApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanApplication(arg0);
                return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanApplication(arg0);
            return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<{
        totalGalleryItems: bigint;
        totalKYC: bigint;
        totalLoans: bigint;
        totalFranchises: bigint;
        totalLetters: bigint;
        totalUsers: bigint;
        totalDocuments: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUser(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: LoginAttempt): Promise<{
        user?: User;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0);
                return from_candid_record_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0);
            return from_candid_record_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectFranchiseApplication(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFranchiseApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFranchiseApplication(arg0, arg1);
            return result;
        }
    }
    async rejectKYC(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectKYC(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectKYC(arg0);
            return result;
        }
    }
    async rejectLoanApplication(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLoanApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLoanApplication(arg0, arg1);
            return result;
        }
    }
    async submitFranchiseApplication(arg0: FranchiseApplicationCreatePayload): Promise<FranchiseApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFranchiseApplication(arg0);
                return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFranchiseApplication(arg0);
            return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitKYC(arg0: KYCRecordCreatePayload): Promise<KYCRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKYC(await to_candid_KYCRecordCreatePayload_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKYC(await to_candid_KYCRecordCreatePayload_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLoanApplication(arg0: LoanApplicationCreatePayload): Promise<LoanApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLoanApplication(arg0);
                return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLoanApplication(arg0);
            return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDocument(arg0: string, arg1: Document): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, await to_candid_Document_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, await to_candid_Document_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFranchiseApplication(arg0: FranchiseApplicationUpdatePayload): Promise<FranchiseApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFranchiseApplication(arg0);
                return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFranchiseApplication(arg0);
            return from_candid_FranchiseApplication_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGalleryItem(arg0: string, arg1: GalleryItem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryItem(arg0, await to_candid_GalleryItem_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryItem(arg0, await to_candid_GalleryItem_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateKYCRecord(arg0: KYCRecordUpdatePayload): Promise<KYCRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKYCRecord(await to_candid_KYCRecordUpdatePayload_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKYCRecord(await to_candid_KYCRecordUpdatePayload_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_KYCRecord_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLetter(arg0: string, arg1: Letter): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLetter(arg0, to_candid_Letter_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLetter(arg0, to_candid_Letter_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLoanApplication(arg0: LoanApplicationUpdatePayload): Promise<LoanApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoanApplication(arg0);
                return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoanApplication(arg0);
            return from_candid_LoanApplication_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserUpdatePayload): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(await to_candid_UserUpdatePayload_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(await to_candid_UserUpdatePayload_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyKYC(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyKYC(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyKYC(arg0);
            return result;
        }
    }
}
function from_candid_AdminRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminRole): AdminRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FranchiseApplication_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FranchiseApplication): FranchiseApplication {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_FranchiseStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FranchiseStatus): FranchiseStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_KYCRecord_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYCRecord): Promise<KYCRecord> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_KYCStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYCStatus): KYCStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_LetterStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterStatus): LetterStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Letter_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Letter): Letter {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplication_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_LoanStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PaperSize_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaperSize): PaperSize {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Promise<Document | null> {
    return value.length === 0 ? null : await from_candid_Document_n9(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryItem]): Promise<GalleryItem | null> {
    return value.length === 0 ? null : await from_candid_GalleryItem_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Letter]): Letter | null {
    return value.length === 0 ? null : from_candid_Letter_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    size: bigint;
    description: string;
    docType: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    description: string;
    docType: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        size: value.size,
        description: value.description,
        docType: value.docType,
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    blob: _ExternalBlob;
    description: string;
    category: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        blob: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        category: value.category,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LetterStatus;
    referenceNumber: string;
    subject: string;
    authorityName: string;
    body: string;
    date: bigint;
    designation: string;
    createdAt: bigint;
    paperSize: _PaperSize;
    recipientAddress: string;
    recipientName: string;
}): {
    status: LetterStatus;
    referenceNumber: string;
    subject: string;
    authorityName: string;
    body: string;
    date: bigint;
    designation: string;
    createdAt: bigint;
    paperSize: PaperSize;
    recipientAddress: string;
    recipientName: string;
} {
    return {
        status: from_candid_LetterStatus_n20(_uploadFile, _downloadFile, value.status),
        referenceNumber: value.referenceNumber,
        subject: value.subject,
        authorityName: value.authorityName,
        body: value.body,
        date: value.date,
        designation: value.designation,
        createdAt: value.createdAt,
        paperSize: from_candid_PaperSize_n22(_uploadFile, _downloadFile, value.paperSize),
        recipientAddress: value.recipientAddress,
        recipientName: value.recipientName
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    createdAt: bigint;
    role: _AdminRole;
    fullName: string;
    isActive: boolean;
    email: string;
    profilePhotoBlob: [] | [_ExternalBlob];
    passwordHash: Uint8Array;
    phone: string;
    walletBalance: bigint;
}): Promise<{
    id: string;
    username: string;
    createdAt: bigint;
    role: AdminRole;
    fullName: string;
    isActive: boolean;
    email: string;
    profilePhotoBlob?: ExternalBlob;
    passwordHash: Uint8Array;
    phone: string;
    walletBalance: bigint;
}> {
    return {
        id: value.id,
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_AdminRole_n30(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        profilePhotoBlob: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.profilePhotoBlob)),
        passwordHash: value.passwordHash,
        phone: value.phone,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _FranchiseStatus;
    areaPreference: string;
    investmentCapacity: string;
    city: string;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    businessExperience: string;
    state: string;
    address: string;
    phone: string;
}): {
    id: string;
    status: FranchiseStatus;
    areaPreference: string;
    investmentCapacity: string;
    city: string;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    businessExperience: string;
    state: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_FranchiseStatus_n37(_uploadFile, _downloadFile, value.status),
        areaPreference: value.areaPreference,
        investmentCapacity: value.investmentCapacity,
        city: value.city,
        userId: value.userId,
        createdAt: value.createdAt,
        fullName: value.fullName,
        adminNote: value.adminNote,
        businessExperience: value.businessExperience,
        state: value.state,
        address: value.address,
        phone: value.phone
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _KYCStatus;
    userId: string;
    submittedAt: bigint;
    panNumber: string;
    aadhaarNumber: string;
    photo: _ExternalBlob;
    verifiedAt: [] | [bigint];
    panDoc: _ExternalBlob;
    aadhaarDoc: _ExternalBlob;
}): Promise<{
    id: string;
    status: KYCStatus;
    userId: string;
    submittedAt: bigint;
    panNumber: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
    verifiedAt?: bigint;
    panDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_KYCStatus_n43(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        submittedAt: value.submittedAt,
        panNumber: value.panNumber,
        aadhaarNumber: value.aadhaarNumber,
        photo: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photo),
        verifiedAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.verifiedAt)),
        panDoc: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.panDoc),
        aadhaarDoc: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.aadhaarDoc)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LoanStatus;
    documents: string;
    loanAmount: bigint;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    address: string;
    existingLoans: string;
    phone: string;
    purpose: string;
    monthlyIncome: string;
}): {
    id: string;
    status: LoanStatus;
    documents: string;
    loanAmount: bigint;
    userId: string;
    createdAt: bigint;
    fullName: string;
    adminNote: string;
    address: string;
    existingLoans: string;
    phone: string;
    purpose: string;
    monthlyIncome: string;
} {
    return {
        id: value.id,
        status: from_candid_LoanStatus_n50(_uploadFile, _downloadFile, value.status),
        documents: value.documents,
        loanAmount: value.loanAmount,
        userId: value.userId,
        createdAt: value.createdAt,
        fullName: value.fullName,
        adminNote: value.adminNote,
        address: value.address,
        existingLoans: value.existingLoans,
        phone: value.phone,
        purpose: value.purpose,
        monthlyIncome: value.monthlyIncome
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: [] | [_User];
    error: [] | [string];
}): Promise<{
    user?: User;
    error?: string;
}> {
    return {
        user: record_opt_to_undefined(await from_candid_opt_n56(_uploadFile, _downloadFile, value.user)),
        error: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finalized: null;
} | {
    draft: null;
}): LetterStatus {
    return "finalized" in value ? LetterStatus.finalized : "draft" in value ? LetterStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    a4: null;
} | {
    a5: null;
} | {
    legal: null;
} | {
    letter: null;
}): PaperSize {
    return "a4" in value ? PaperSize.a4 : "a5" in value ? PaperSize.a5 : "legal" in value ? PaperSize.legal : "letter" in value ? PaperSize.letter : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    standard: null;
}): AdminRole {
    return "admin" in value ? AdminRole.admin : "standard" in value ? AdminRole.standard : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): FranchiseStatus {
    return "pending" in value ? FranchiseStatus.pending : "approved" in value ? FranchiseStatus.approved : "rejected" in value ? FranchiseStatus.rejected : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): KYCStatus {
    return "verified" in value ? KYCStatus.verified : "pending" in value ? KYCStatus.pending : "rejected" in value ? KYCStatus.rejected : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n9(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FranchiseApplication>): Array<FranchiseApplication> {
    return value.map((x)=>from_candid_FranchiseApplication_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n12(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KYCRecord>): Promise<Array<KYCRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_KYCRecord_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Letter>): Array<Letter> {
    return value.map((x)=>from_candid_Letter_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplication>): Array<LoanApplication> {
    return value.map((x)=>from_candid_LoanApplication_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Promise<Array<User>> {
    return await Promise.all(value.map(async (x)=>await from_candid_User_n28(_uploadFile, _downloadFile, x)));
}
function to_candid_AdminRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminRole): _AdminRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_Document_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): Promise<_Document> {
    return await to_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_GalleryItem_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryItem): Promise<_GalleryItem> {
    return await to_candid_record_n63(_uploadFile, _downloadFile, value);
}
async function to_candid_KYCRecordCreatePayload_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCRecordCreatePayload): Promise<_KYCRecordCreatePayload> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_KYCRecordUpdatePayload_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCRecordUpdatePayload): Promise<_KYCRecordUpdatePayload> {
    return await to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_LetterStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterStatus): _LetterStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Letter_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Letter): _Letter {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_PaperSize_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaperSize): _PaperSize {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_UserCreatePayload_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserCreatePayload): Promise<_UserCreatePayload> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function to_candid_UserUpdatePayload_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserUpdatePayload): Promise<_UserUpdatePayload> {
    return await to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: AdminRole;
    fullName: string;
    email: string;
    profilePhotoBlob?: ExternalBlob;
    passwordHash: Uint8Array;
    phone: string;
}): Promise<{
    username: string;
    role: _AdminRole;
    fullName: string;
    email: string;
    profilePhotoBlob: [] | [_ExternalBlob];
    passwordHash: Uint8Array;
    phone: string;
}> {
    return {
        username: value.username,
        role: to_candid_AdminRole_n26(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        email: value.email,
        profilePhotoBlob: value.profilePhotoBlob ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.profilePhotoBlob)) : candid_none(),
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    panNumber: string;
    aadhaarNumber: string;
    photo: ExternalBlob;
    panDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}): Promise<{
    userId: string;
    panNumber: string;
    aadhaarNumber: string;
    photo: _ExternalBlob;
    panDoc: _ExternalBlob;
    aadhaarDoc: _ExternalBlob;
}> {
    return {
        userId: value.userId,
        panNumber: value.panNumber,
        aadhaarNumber: value.aadhaarNumber,
        photo: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.photo),
        panDoc: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.panDoc),
        aadhaarDoc: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.aadhaarDoc)
    };
}
async function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
    name: string;
    size: bigint;
    description: string;
    docType: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
    name: string;
    size: bigint;
    description: string;
    docType: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        size: value.size,
        description: value.description,
        docType: value.docType,
        uploadedAt: value.uploadedAt
    };
}
async function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
    uploadedAt: bigint;
}): Promise<{
    id: string;
    title: string;
    blob: _ExternalBlob;
    description: string;
    category: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        blob: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        category: value.category,
        uploadedAt: value.uploadedAt
    };
}
async function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    record: KYCRecordCreatePayload;
}): Promise<{
    id: string;
    record: _KYCRecordCreatePayload;
}> {
    return {
        id: value.id,
        record: await to_candid_KYCRecordCreatePayload_n58(_uploadFile, _downloadFile, value.record)
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LetterStatus;
    referenceNumber: string;
    subject: string;
    authorityName: string;
    body: string;
    date: bigint;
    designation: string;
    createdAt: bigint;
    paperSize: PaperSize;
    recipientAddress: string;
    recipientName: string;
}): {
    status: _LetterStatus;
    referenceNumber: string;
    subject: string;
    authorityName: string;
    body: string;
    date: bigint;
    designation: string;
    createdAt: bigint;
    paperSize: _PaperSize;
    recipientAddress: string;
    recipientName: string;
} {
    return {
        status: to_candid_LetterStatus_n16(_uploadFile, _downloadFile, value.status),
        referenceNumber: value.referenceNumber,
        subject: value.subject,
        authorityName: value.authorityName,
        body: value.body,
        date: value.date,
        designation: value.designation,
        createdAt: value.createdAt,
        paperSize: to_candid_PaperSize_n14(_uploadFile, _downloadFile, value.paperSize),
        recipientAddress: value.recipientAddress,
        recipientName: value.recipientName
    };
}
async function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    user: UserCreatePayload;
}): Promise<{
    id: string;
    user: _UserCreatePayload;
}> {
    return {
        id: value.id,
        user: await to_candid_UserCreatePayload_n24(_uploadFile, _downloadFile, value.user)
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaperSize): {
    a4: null;
} | {
    a5: null;
} | {
    legal: null;
} | {
    letter: null;
} {
    return value == PaperSize.a4 ? {
        a4: null
    } : value == PaperSize.a5 ? {
        a5: null
    } : value == PaperSize.legal ? {
        legal: null
    } : value == PaperSize.letter ? {
        letter: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterStatus): {
    finalized: null;
} | {
    draft: null;
} {
    return value == LetterStatus.finalized ? {
        finalized: null
    } : value == LetterStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminRole): {
    admin: null;
} | {
    standard: null;
} {
    return value == AdminRole.admin ? {
        admin: null
    } : value == AdminRole.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
